<template>
    <v-card style="background: none;" transparent dark flat>
        <h1 class="ml-10 subtitle">Development <span class="primary--text">Projects</span></h1>
            <v-card style="clear: both;" transparent flat :class="(index % 2 ? 'float-right ' : 'float-left ml-10 ') + 'ma-3 project-card-border pa-5 rounded-xl'" max-width="600px" v-for="(project, index) in projects" :key="index">
                <div :class="index % 2 ? 'text-right' : ''">
                    <h3>{{ project.title }}</h3>
                    <div class="project-description">
                        <p>{{ project.description }}</p>
                    </div>
                    <v-chip class="mr-2" v-for="(tech, index) in project.techno" :key="index"> {{ tech }} </v-chip>
                    <v-btn target="_blank" v-if="project.link" icon :href="project.link"><v-icon>mdi-open-in-new</v-icon></v-btn>
                </div>
            </v-card>
    </v-card>
</template>
<script>
export default {
  data () {
    return {
        projects:[
            {
                title:"Customer area design",
                description:"began designing a secure customer interface where customers would be able to check delivery times, make alterations, place orders, receive notifications and communicate information.",
                techno:["NUXT","Vue","CSS","HTML","JavaScript", "Node"]
            },
            {
                title:"Infime Project",
                description:"Creation of an information page for a TV. This one gathers different information like train schedules, company events, etc... As well as an administration page for the modifications and an API to communicate between the two interfaces",
                techno:["NUXT","Vue","CSS","HTML","JavaScript", "Node"]
            },
            {
                title:"EasySave",
                description:"EasySave is a backup software. It allows to save data (files, folders, etc.) by storing it on another support (external hard drive, cloud, etc.). The purpose is to protect the data in case of loss or damage to the original support. The user can choose the data to be saved and the type of backup.", 
                link:["https://dev.azure.com/grp7prosoft/EasySave"], 
                techno:["C#",".NET Core","DevOps","MVVM"]
            },
            {
                title:"ANIMUS EXTENDUS",
                description:"The project involves analyzing the existing infrastructure, providing a report on identity management and data access, presenting a new infrastructure with a complementary mock-up, demonstrating discovery and automation scripts, with a focus on security, and providing all the documentation and procedures used in the project to the future administrator.", 
                techno:["Active Directory","Pfsense","Ipsec", "and more"]
            },
            {
                title:"Cloud Healthcare Unit",
                description:"Implements a data warehouse to leverage data generated by care management and FTP systems. Provides a complete solution to extract, store, explore and visualize this data. Integrates data from distributed files into a single persistent source. Highly secure data from care management system histories.", 
                techno:["Talend", "Cloudera"]
            },
            {
                title:"MININF POO project",
                description:"The project consists in creating an application with a graphical interface based on WinForms and using the C++ programming language. This application will allow to manage the staff, the customers and their orders, as well as the stock of electronic components for an online sales company. It also includes a statistical functionality to calculate and analyze the collected data.", 
                techno:["C++", "SQL","MVC","POO"],
                link:["https://github.com/clement15613/Projet_POO/tree/main"]
            },
            {
                title:"Web Cesi project",
                description:"The objective of the project is to create an application space to allow students to apply for internship offers that tutors make available. There is also a notification system integrated to the site to know the progress of the application ", 
                techno:["PHP","HTML","CSS","JavaScript","SQL"],
                link:["https://github.com/clement15613/ProjetWeb"]
            },

        ]
    }
  },
}
</script>
<style>
.project-card-border:hover{
    border:1px solid #1976d2 !important;
    transition: 0.3s;
}
.project-card-border{
    border: 1px solid #565656 !important;
}
</style>